SeasonTrackerWebApp/SeasonTracker/Controllers/Api/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Data.Entity;
using System.Web.Http;
using SeasonTracker.Models;
using SeasonTracker.Dtos;
using AutoMapper;

/*
 * API Controller
 */
namespace SeasonTracker.Controllers.Api
{
    public class MembersController : ApiController
    {
        private ApplicationDbContext _context;

        public MembersController()
        {
            _context = new ApplicationDbContext();
        }

        /*
         * Method: In use
         */
        //We want to return a list of members.
        //This is the convention built into ASP.NET Web API:
        // GET /api/members
        // OR
        // GET /api/members?id=4
        //
        public IEnumerable<MemberDto> GetMembers(string query = null)
        {
            //In order to eager load the account type, we need to "include" it.
            //Because the member data context includes the AccountTypeId, this sort of cross-references it.
            //var memberDtos = _context.Members
            //    .Include(m => m.AccountType)
            //    .ToList()
            //    .Select(Mapper.Map<Member, MemberDto>);

            //return Ok(memberDtos);

            var membersQuery = _context.Members
                .Include(m => m.AccountType);

            if (!String.IsNullOrWhiteSpace(query))
                membersQuery = membersQuery.Where(m => m.Id == Convert.ToInt16(query));

            return membersQuery
                .ToList()
                .Select(Mapper.Map<Member, MemberDto>);
        }

        /*
         * Method: TBD
         */
        //We want to return a single member.
        //This will respond to a request like this:
        // GET /api/members/1
        public IHttpActionResult GetMember(int id)
        {
            //get the member
            var member = _context.Members
                .Include(m => m.AccountType)
                .SingleOrDefault(c => c.Id == id);

            //if the member is not found
            if (member == null)
                return NotFound();

            //otherwise return the member
            //TBD: need to return the view
            return Ok(Mapper.Map<Member, MemberDto>(member));
        }

        /*
         * Method: TBD
         */
        //To create a member, post a member to members collection:
        // POST /api/members
        [HttpPost]  //we do this because we are 'creating' a resource, not getting one.
        public IHttpActionResult CreateMember(MemberDto memberDto)
        {
            //First we validate the object, and throw exception if model is not valid
            if (!ModelState.IsValid)
                return BadRequest();

            //We need to map the memberDto back to our domain model.
            var member = Mapper.Map<MemberDto, Member>(memberDto);

            //otherwise we add it to our context and save the changes
            _context.Members.Add(member);
            _context.SaveChanges();

            memberDto.Id = member.Id;

            //At this point the Id of the member will be generated by the server and be returned by the object.
            //As part of RESTful convention, we need to return the URI of the newly created resource to the client.
            //i.e. /api/members/10
            return Created(new Uri(Request.RequestUri + "/" + member.Id), memberDto);

        }

        /*
         * Method: TBD
         */
        //To update a member:
        // PUT /api/members/1
        [HttpPut]
        public IHttpActionResult UpdateMember(int id, MemberDto memberDto)
        {
            //First we validate the object, and throw exception if model is not valid
            if (!ModelState.IsValid)
                return BadRequest();

            var memberInDb = _context.Members.SingleOrDefault(c => c.Id == id);

            //It's possible that the client sends an invalid Id so we need to check for the existence of the object.
            if (memberInDb == null)
                return NotFound();

            Mapper.Map(memberDto, memberInDb);

            _context.SaveChanges();

            return Ok();
        }

        /*
         * Method: In use
         */
        //To delete a member:
        // DELETE /api/members/1
        [HttpDelete]
        public IHttpActionResult DeleteMember(int id)
        {
            var memberInDb = _context.Members.SingleOrDefault(c => c.Id == id);

            //It's possible that the client sends an invalid Id so we need to check for the existence of the object.
            if (memberInDb == null)
                return NotFound();

            _context.Members.Remove(memberInDb);

            _context.SaveChanges();

            return Ok();
        }
    }
}

SeasonTrackerWebApp/SeasonTracker/Controllers/Api/WatchListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Data.Entity;
using System.Web.Http;
using SeasonTracker.Models;
using SeasonTracker.Dtos;
using AutoMapper;

/*
 * API Controller
 */
namespace SeasonTracker.Controllers.Api
{
    public class WatchListsController : ApiController
    {
        private ApplicationDbContext _context;

        public WatchListsController()
        {
            _context = new ApplicationDbContext();
        }

        //We want to return a list of watchlists.
        //This is the convention built into ASP.NET Web API:
        // GET /api/watchlists
        public IHttpActionResult GetWatchLists()
        {
            var watchListDtos = _context.WatchLists
                .Include(m => m.Member)
                .Include(m => m.TvShow)
                .ToList()
                .Select(Mapper.Map<WatchList, WatchListDto>);

            return Ok(watchListDtos);
        }

        //We want to return a list of watchlists based on the member Id.
        //This is the convention built into ASP.NET Web API:
        // GET /api/watchlists/member/6
        //TBD - will need to come back to later in the course. Might be able to solve with 
        //something like query string:
        //public IEnumerable<MovieDto> GetMovies(string query = null)
        //{
        //    var moviesQuery = _context.Movies
        //        .Include(m => m.Genre)
        //        .Where(m => m.NumberAvailable > 0);

        //    if (!String.IsNullOrWhiteSpace(query))
        //        moviesQuery = moviesQuery.Where(m => m.Name.Contains(query));

        //    return moviesQuery
        //        .ToList()
        //        .Select(Mapper.Map<Movie, MovieDto>);
        //}
        //[Route("api/watchlists/dashboard/{id}")]      //Custom api route
        //public IHttpActionResult GetWatchListsByMember(int? id)
        //{
        //    var watchList = _context.WatchLists
        //        .Include(m => m.TvShow)
        //        .Where(m => m.Id == id)
        //        .SingleOrDefault();

        //    //var watchList = _context.Members
        //    //    .Include(m => m.WatchLists)
        //    //    .Where(m => m.Id == id)
        //    //    .SingleOrDefault();

        //    if (watchList == null)
        //        return (null);

        //    return Ok(Mapper.Map<WatchList,WatchListDto>(watchList));
        //}

        //We want to return a single watch list given by the watchlist Id.
        //This will respond to a request like this:
        // GET /api/watchlists/1
        //public IHttpActionResult GetWatchList(int id)
        //{
        //    //get the watch list
        //    var watchList = _context.WatchLists.SingleOrDefault(c => c.Id == id);

        //    //if the watchList is not found
        //    if (watchList == null)
        //        return NotFound();

        //    //otherwise return the watchList
        //    return Ok(Mapper.Map<WatchList, WatchListDto>(watchList));
        //}

        //We want to return all watchlists for a given member Id.
        //This will respond to a request like this:
        // GET /api/watchlists/1
        public IEnumerable<WatchListDto> GetWatchList(int id)
        {
            var watchList = _context.WatchLists
                .Include(t => t.TvShow)
                .Include(t => t.Member)
                .Where(t => t.Member.Id == id)
                //.Single();
                .ToList();

            //get the watch list
            //var watchList = _context.WatchLists.SingleOrDefault(c => c.Id == id);

            //if the watchList is not found
            //if (watchList == null)
            //    return NotFound();

            //otherwise return the watchList
            //return Ok(Mapper.Map<WatchList, WatchListDto>(watchList));
            return watchList
                .Select(Mapper.Map<WatchList, WatchListDto>);
        }

        






















        //To create a watchlist, post a watchlist to watchlist collection:
        // POST /api/watchlists
        //[HttpPost]  //we do this because we are 'creating' a resource, not getting one.
        //public IHttpActionResult CreateWatchList(WatchListDto watchListDto)
        //{
        //    //First we validate the object, and throw exception if model is not valid
        //    if (!ModelState.IsValid)
        //        return BadRequest();

        //    //We need to map the watchListDto back to our domain model.
        //    var watchList = Mapper.Map<WatchListDto, WatchList>(watchListDto);

        //    //otherwise we add it to our context and save the changes
        //    _context.WatchLists.Add(watchList);
        //    _context.SaveChanges();

        //    watchListDto.Id = watchList.Id;

        //    //At this point the Id of the watchlist will be generated by the server and be returned by the object.
        //    //As part of RESTful convention, we need to return the URI of the newly created resource to the client.
        //    //i.e. /api/watchlists/10
        //    return Created(new Uri(Request.RequestUri + "/" + watchList.Id), watchListDto);
        //}


        //[Route("watchlists/add/{mId}/{tId}")]




        //To update a watchlist:
        // PUT /api/watchlists/1
        [HttpPut]
        public IHttpActionResult UpdateWatchList(int id, WatchListDto watchListDto)
        {
            //First we validate the object, and throw exception if model is not valid
            if (!ModelState.IsValid)
                return BadRequest();

            var watchListInDb = _context.WatchLists.SingleOrDefault(c => c.Id == id);

            //It's possible that the client sends an invalid Id so we need to check for the existence of the object.
            if (watchListInDb == null)
                return NotFound();

            Mapper.Map(watchListDto, watchListInDb);

            _context.SaveChanges();

            return Ok();
        }

        //To delete a watchlist:
        // DELETE /api/watchlists/1
        [HttpDelete]
        public IHttpActionResult DeleteWatchList(int id)
        {
            var watchListInDb = _context.WatchLists.SingleOrDefault(c => c.Id == id);

            //It's possible that the client sends an invalid Id so we need to check for the existence of the object.
            if (watchListInDb == null)
                return NotFound();

            _context.WatchLists.Remove(watchListInDb);

            _context.SaveChanges();

            return Ok();
        }
    }
}

SeasonTrackerWebApp/SeasonTracker/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;
using SeasonTracker.Models;
using SeasonTracker.ViewModels;

/*
 * MVC Controller
 */
namespace SeasonTracker.Controllers
{
    public class MembersController : Controller
    {
        //In order to query the database, we need to create a database context. 
        private ApplicationDbContext _context;

        //Create a constructor for the MembersController that creates the DbContext for this
        //controller.
        public MembersController()
        {
            _context = new ApplicationDbContext();
        }

        //The DbContext is a disposable object, se we need to properly dispose of the object.
        //So the proper way to do it is to override the dispose method of the base controller class.
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        /*
         * Method: In use
         */
        //Display the member form with a list of the account types
        public ActionResult New()
        {
            //First get the list of the account types
            var accountTypes = _context.AccountTypes.ToList();

            //Use a View Model that encapsulates all of the data required for this view
            var viewModel = new MemberFormViewModel
            {
                //On a new member, create a member object so the Id gets initialized in the form.
                Member = new Member(),
                //Set the list of accountTypes to the view models' AccountTypes property
                AccountTypes = accountTypes
            };

            return View("MemberForm", viewModel);
        }

        /*
         * Method: In use
         */
        //Define the 'Save' action for Member. This is model binding. MVC framework binds
        //this model to the request data.
        //Here we are saving/persiting data to the database.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Member member)
        {
            //Use modelstate property to get access to validatation data.
            //Since we are requiring the Name property of Member model,
            //we want to return the MemberForm if the field is empty. So need 
            //to define the viewModel and return the form.
            if (!ModelState.IsValid)
            {
                var viewModel = new MemberFormViewModel
                {
                    Member = member,
                    AccountTypes = _context.AccountTypes.ToList()

                };

                return View("MemberForm", viewModel);
            }

            //if the member Id is 0, then we have a new member
            if (member.Id == 0)
                //To save the data to the database, we need to create a context to it.
                _context.Members.Add(member);
            else
            {
                //Using the Single method here because if the given member is not found, 
                //we want to throw an exception. This action should only be called anyways because of posting
                //the member form.
                var memberInDb = _context.Members.Single(m => m.Id == member.Id);

                memberInDb.MemberName = member.MemberName;
                memberInDb.AccountTypeId = member.AccountTypeId;
                memberInDb.IsSubscribedToNewsLetter = member.IsSubscribedToNewsLetter;
            }

            //Persist the changes. This creates SQL statements at runtime, within a transaction.
            _context.SaveChanges();

            //Now redirect the members to the members page "Index"
            return RedirectToAction("Index", "Members");
        }

        /*
         * Method: In use
         */
        // GET: Members
        // This is what renders the "Index" page to display all Members. The Index page calls 
        // /api/members
        public ViewResult Index()
        {
            return View();
        }

        /*
         * Method: In use
         */
        //This is the action that is processed when the "Details" page is rendered.
        public ActionResult Details(int id)
        {
            //When the Index page is loaded, each user is displayed with an ActionLink that processes this "Details" action method.
            var member = _context.Members
                .Include(m => m.AccountType)
                .SingleOrDefault(m => m.Id == id);

            if (member == null)
                return HttpNotFound();

            //A view is rendered for a specific user
            return View(member);
        }

        /*
         * Method: In use
         */
        //This displays the MemberForm for editing
        public ActionResult Edit(int id)
        {
            //First we need to get this member with the member id from the database.
            //If the member with the given id exists it will be returned, otherwise null.
            var member = _context.Members.SingleOrDefault(c => c.Id == id);

            if (member == null)
                return HttpNotFound();

            //New we need to render the members edit form, which is based on the View Model, and specify the 
            //view name.
            var viewModel = new MemberFormViewModel
            {
                Member = member,
                AccountTypes = _context.AccountTypes.ToList()
            };
            return View("MemberForm", viewModel);
        }
    }
}

SeasonTrackerWebApp/SeasonTracker/Views/WatchLists/Add.cshtml
@model  SeasonTracker.ViewModels.TvShowSelectionViewModel
@{
    ViewBag.Title = "Add a Tv Show";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*Display the member name and the TV Shows they can subscribe to*@
<h2>Add a new Tv Show to your list, @Model.Member.MemberName</h2>
<table id="tvshows-table" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Add</th>
            <th>Tv Show Name</th>
            <th>Season Number</th>
            <th>Number of Episodes</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

@section scripts
{
    <script>
        $(document).ready(function () {
            var table = $("#tvshows-table").DataTable({
                ajax: {
                    url: "/api/tvShows",
                    dataSrc: ""
                },
                columns: [
                    {
                        data: "id",
                        render: function (data) {
                            return "<button class='btn-link js-Add' data-tvshow-id=" + data + ">Add</button>";
                        }
                    },
                    {
                        data: "tvShowName",
                        render: function (data, type, tvShow) {
                            return "<a href='/tvshows/edit/" + tvShow.id + "'>" + tvShow.tvShowName + "</a>";
                        }
                    },
                    {
                        data: "seasonNumber"
                    },
                    {
                        data: "numberOfEpisodes"
                    }
                ]
            });

            //NOTE/TBD: here's where I want to implement an interface similar to the adding new rentals.
            $("#tvshows-table").on("click", ".js-add", function () {
                var button = $(this);
                bootbox.confirm("Are you sure you want to add this Tv Show?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/api/tvshows/" + button.attr("data-tvshow-id"),
                            method: "CREATE",
                            success: function () {
                                alert("Tv Show Added!")
                            },
                            error: function() {
                                alert("Tv Show not added. Something went wrong.");
                            }
                        });
                    }
                });
            });
        });
    </script>
}

SeasonTrackerWebApp/SeasonTracker/Views/WatchLists/Dashboard.cshtml
@model  SeasonTracker.ViewModels.WatchListViewModel
@{
    ViewBag.Title = "Member Dashboard";
}

@*Display the member name and the TV Shows they are subscribed to*@
<h2>Watchlist Dashboard for member: @Model.MemberId</h2>

<form id="newWatchList">
    <div class="form-group">
        <label>Search for New Tv Show</label>
        <div class="tt-container">
            <input id="tvShow" type="text" value="" class="form-control" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-sm-4">
            <ul id="tvShows" class="list-group"></ul>
        </div>
    </div>
    <button class="btn btn-primary">Add</button>
    <br />
    <br />
</form>

<table id="member-watchlist-table" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Member Id</th>
            <th>Watch List Id</th>
            <th>Tv Show</th>
            <th>Season Number</th>
            <th>Viewing List</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {

            /*
             * Javascript for typeahead
             * This is javascript from: https://twitter.github.io/typeahead.js/examples/#remote
             * Bloodhound is the suggestion engine behind typeahead.
             *
             */

            //vm - 'view model' on the client.
            //When the member submits the form, this vm will be sent to the newWatchLists api
            //"CreateNewWatchLists"
            var vm = {
                //initialize a property to an empty array.
                tvShowIds: []
            };

            //We want to tokenize 'name' of the tv show.
            //Note: I commented out the prefetch so I could actually get tv show data from a json file.
            //Note 2: %QUERY gets replaced with what the user puts in the text box at runtime
            var tvShows = new Bloodhound({
                //Look at the tv show name property of tvShows
                datumTokenizer: Bloodhound.tokenizers.obj.whitespace('tvShowName'),
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                //Prefetch provides data and additional requests from server
                //prefetch: '../data/films/post_1960.json',
                remote: {
                    //url: '../data/films/queries/%QUERY.json',
                    url: '/api/tvshows?query=%QUERY',
                    wildcard: '%QUERY'
                }
            });

            //Here is a refernce to our textbox, giving the 'id' of the input text box
            //minLength - this is the minimum length a user needs to type before querying the server
            //highlight - highlights the matching characters
            $('#tvShow').typeahead({
                minLength: 3,
                highlight: true
            }, {
                //name - is the 'tvShows' model
                //display - what property we should display in the suggestion list
                //source - is the source of our bloodhound object declared by 'var' above
                name: 'tvShows',
                display: 'tvShowName',
                source: tvShows
                //e is the event
                //'tvShow' is the selected tv show
            }).on("typeahead:select", function (e, tvShow) {
                //Append the tv show from the element with the id 'tvShows', and add the name of the movie
                $("#tvShows").append("<li class='list-group-item'>" + tvShow.tvShowName + "</li>");

                //Get the movie element and specify the property we want to update
                $("#tvShow").typeahead("val", "");

                //Associate the member Id with the tv show Id to add to the watchlist
                vm.memberId = @Model.MemberId;
                vm.tvShowIds.push(tvShow.id);
            });

            //Here, we get the form with the id "newWatchList" and handle the submit function.
            //e represents the submit event.
            $("#newWatchList").submit(function (e) {
                //This will prevent the form from submitting normally. Need this in order to use Ajax.
                e.preventDefault();

                //Then we can use Ajax to submit the view model 
                $.ajax({
                    url: "/api/newWatchLists",  //the api controller.
                    method: "post",
                    data: vm                    //represents our dto expected by the api controller
                })
                .done(function () {
                    toastr.success("Watchlist successfully recorded.");
                })
                .fail(function () {
                    toastr.error("Something unexpected occured.");
                });
            });

            /*
             * Display the data in a table.
             *
             */
            var table = $("#member-watchlist-table").DataTable({
                ajax: {
                    url: "/api/watchlists/" + "@Model.MemberId",
                    dataSrc: ""
                },
                columns: [
                    {
                        data: "member.id"
                        //defaultContent: "tvShowName"
                    },
                    {
                        //data: "seasonNumber"
                        data: "id"
                        //defaultContent: "tvShowName"
                    },
                    {
                        data: "tvShow.tvShowName"
                        //defaultContent: "tvShowName"
                    },
                    {
                        data: "tvShow.seasonNumber"
                        //defaultContent: "tvShowName"
                    },
                    {
                        data: "viewingList"
                        //defaultContent: "tvShowName"
                    }
                ]
            });
        });
    </script>


}

SeasonTrackerWebApp/SeasonTracker/Views/WatchLists/Edit.cshtml
@model  SeasonTracker.ViewModels.WatchListFormViewModel
@{
    ViewBag.Title = "Watchlist - " + @Model.TvShow.TvShowName;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*Display the member name and the TV Shows they are subscribed to*@
<h2>@Model.TvShow.TvShowName : Season @Model.TvShow.SeasonNumber</h2>
@*This creates a form block*@
@using (Html.BeginForm("Save", "WatchLists"))
{
    //There is special markup that we need to use here that is used
    //by Bootstrap to render dynamic forms. The classes defined here are
    //used by bootstrap to style the form and its controls.
    <div class="form-group">
        @Html.LabelFor(m => m.WatchList.ViewingList)
        @Html.TextBoxFor(m => m.WatchList.ViewingList, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.WatchList.ViewingList)
    </div>
    //Because the properties in this form relies on the Id in order to save to the database, we
    //need to make this field hidden. This is an arbitrary place for it, just cleaner to put it here.
    @Html.HiddenFor(m => m.WatchList.Id)
    //This creates a token and then puts it in this form as a hidden field and also as a cookie on the users computer.
    //This prevents a hacker from gaining access to the form data and sending a request on behalf of the user. This
    //token can be viewed in the inspect window for the form and needs to match with the token contained in the cookie
    //which can be viewed from Chrome inspect/Application/Cookies/localhost
    @Html.AntiForgeryToken()
    //go to getbootstrap.com to find the class name for button
    <button type="submit" class="btn btn-primary">Save</button>
}
@*Added for client side validation of the fields in this form. This is not enabled by default,
    but you can pull in the path from 'BundleConfig' so that validation comes from the client side,
    not the server side. This is a good practice in situations like this so we don't wait for the
    server to come back and tell us that we didn't fill out the Name text box, for example.

    Note: if client side validation is enabled (like below), ValidationSummary will not work. That is a
            server side summary.
*@
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

SeasonTrackerWebApp/SeasonTracker/Views/WatchLists/Member.cshtml
@model  SeasonTracker.ViewModels.WatchListViewModel
@{
    ViewBag.Title = "Watchlists";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*Display the member name and the TV Shows they are subscribed to*@
<h2>Watchlist for member: @Model.MemberId</h2>
<p>
    @Html.ActionLink("Add", "Add", "WatchLists", new { id = Model.MemberId }, new { @class = "btn btn-primary" })
</p>

<table id="member-watchlist-table" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Member Id</th>
            <th>Watch List Id</th>
            <th>Tv Show</th>
            <th>Season Number</th>
            <th>Viewing List</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

@section scripts
{
    <script>
        $(document).ready(function () {
            var table = $("#member-watchlist-table").DataTable({
                ajax: {
                    url: "/api/watchlists/" + "@Model.MemberId",
                    dataSrc: ""
                },
                columns: [
                    {
                        data: "member.id"
                        //defaultContent: "tvShowName"
                    },
                    {
                        //data: "seasonNumber"
                        data: "id"
                        //defaultContent: "tvShowName"
                    },
                    {
                        data: "tvShow.tvShowName"
                        //defaultContent: "tvShowName"
                    },
                    {
                        data: "tvShow.seasonNumber"
                        //defaultContent: "tvShowName"
                    },
                    {
                        data: "viewingList"
                        //defaultContent: "tvShowName"
                    }
                ]
            });
        });
    </script>
}